spring:
  application:
    name: UserService
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MSSQLServer
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true

server:
  port: 9003