version: '3.8'

services:
  user-service:
    build:
      context: ./user-service
    ports:
      - "9001:9001"
    networks:
      - blog-network
    environment:
      - SPRING_PROFILES_ACTIVE=prod

  post-service:
    build:
      context: ./post-service
    ports:
      - "9002:9002"
    networks:
      - blog-network
    environment:
      - SPRING_PROFILES_ACTIVE=prod

  comment-service:
    build:
      context: ./comment-service
    ports:
      - "9003:9003"
    networks:
      - blog-network
    environment:
      - SPRING_PROFILES_ACTIVE=prod

  api-gateway:
    build:
      context: ./api-gateway
    ports:
      - "9000:9000"
    networks:
      - blog-network
    environment:
      - SPRING_PROFILES_ACTIVE=prod

networks:
  blog-network:
    driver: bridge
