server:
  port: 9000  # Port for the gateway

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970

spring:
  cloud:
    gateway:
      routes:
        - id: user_service
          uri: http://localhost:9001  # User service URL
          predicates:
            - Path=/api/v1/auth/**
            - Path=/api/v1/users/**
        - id: post_service
          uri: http://localhost:9002  # Post service URL
          predicates:
            - Path=/api/posts/**
        - id: comment_service
          uri: http://localhost:9003  # Comment service URL
          predicates:
            - Path=/api/comments/**
